export interface EliteData {
  id: string;
  name: string;
  type: string;
  secondaryType?: string;
  level: number;
  baseStats: {
    hp: number;
    attack: number;
    defense: number;
    speed: number;
  };
  abilities?: string[];
  description: string;
  rarity: 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary';
  color: string;
  isWild: boolean;
  position: [number, number, number];
  evolutionData?: {
    evolvesTo: string;
    evolutionLevel?: number;
    evolutionCondition?: string;
  };
}

export const eliteDatabase: Record<string, EliteData> = {
  // Generation 1 - Kanto Pokemon
  
  // Starter Pokemon
  bulbasaur: {
    id: 'bulbasaur',
    name: 'Bulbasaur',
    type: 'grass',
    secondaryType: 'poison',
    level: 5,
    baseStats: { hp: 45, attack: 49, defense: 49, speed: 45 },
    abilities: ['Overgrow'],
    description: 'A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokémon.',
    rarity: 'uncommon',
    color: '#78C850',
    isWild: true,
    position: [Math.random() * 20 - 10, 0, Math.random() * 20 - 10],
    evolutionData: { evolvesTo: 'ivysaur', evolutionLevel: 16 }
  },
  ivysaur: {
    id: 'ivysaur',
    name: 'Ivysaur',
    type: 'grass',
    secondaryType: 'poison',
    level: 16,
    baseStats: { hp: 60, attack: 62, defense: 63, speed: 60 },
    abilities: ['Overgrow'],
    description: 'When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.',
    rarity: 'rare',
    color: '#78C850',
    isWild: false,
    position: [0, 0, 0],
    evolutionData: { evolvesTo: 'venusaur', evolutionLevel: 32 }
  },
  venusaur: {
    id: 'venusaur',
    name: 'Venusaur',
    type: 'grass',
    secondaryType: 'poison',
    level: 32,
    baseStats: { hp: 80, attack: 82, defense: 83, speed: 80 },
    abilities: ['Overgrow'],
    description: 'The flower on its back releases a soothing scent that enhances emotions.',
    rarity: 'epic',
    color: '#78C850',
    isWild: false,
    position: [0, 0, 0]
  },
  charmander: {
    id: 'charmander',
    name: 'Charmander',
    type: 'fire',
    level: 5,
    baseStats: { hp: 39, attack: 52, defense: 43, speed: 65 },
    abilities: ['Blaze'],
    description: 'Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail.',
    rarity: 'uncommon',
    color: '#F08030',
    isWild: true,
    position: [Math.random() * 20 - 10, 0, Math.random() * 20 - 10],
    evolutionData: { evolvesTo: 'charmeleon', evolutionLevel: 16 }
  },
  charmeleon: {
    id: 'charmeleon',
    name: 'Charmeleon',
    type: 'fire',
    level: 16,
    baseStats: { hp: 58, attack: 64, defense: 58, speed: 80 },
    abilities: ['Blaze'],
    description: 'When it swings its burning tail, it elevates the temperature to unbearably hot levels.',
    rarity: 'rare',
    color: '#F08030',
    isWild: false,
    position: [0, 0, 0],
    evolutionData: { evolvesTo: 'charizard', evolutionLevel: 36 }
  },
  charizard: {
    id: 'charizard',
    name: 'Charizard',
    type: 'fire',
    secondaryType: 'flying',
    level: 36,
    baseStats: { hp: 78, attack: 84, defense: 78, speed: 100 },
    abilities: ['Blaze'],
    description: 'Spits fire that is hot enough to melt boulders. Known to cause forest fires unintentionally.',
    rarity: 'epic',
    color: '#F08030',
    isWild: false,
    position: [0, 0, 0]
  },
  squirtle: {
    id: 'squirtle',
    name: 'Squirtle',
    type: 'water',
    level: 5,
    baseStats: { hp: 44, attack: 48, defense: 65, speed: 43 },
    abilities: ['Torrent'],
    description: 'After birth, its back swells and hardens into a shell. Powerfully sprays foam from its mouth.',
    rarity: 'uncommon',
    color: '#6890F0',
    isWild: true,
    position: [Math.random() * 20 - 10, 0, Math.random() * 20 - 10],
    evolutionData: { evolvesTo: 'wartortle', evolutionLevel: 16 }
  },
  wartortle: {
    id: 'wartortle',
    name: 'Wartortle',
    type: 'water',
    level: 16,
    baseStats: { hp: 59, attack: 63, defense: 80, speed: 58 },
    abilities: ['Torrent'],
    description: 'Often hides in water to stalk unwary prey. For swimming fast, it moves its ears to maintain balance.',
    rarity: 'rare',
    color: '#6890F0',
    isWild: false,
    position: [0, 0, 0],
    evolutionData: { evolvesTo: 'blastoise', evolutionLevel: 36 }
  },
  blastoise: {
    id: 'blastoise',
    name: 'Blastoise',
    type: 'water',
    level: 36,
    baseStats: { hp: 79, attack: 83, defense: 100, speed: 78 },
    abilities: ['Torrent'],
    description: 'A brutal Pokémon with pressurized water jets on its shell. They are used for high-speed tackles.',
    rarity: 'epic',
    color: '#6890F0',
    isWild: false,
    position: [0, 0, 0]
  },

  // Electric Type
  pikachu: {
    id: 'pikachu',
    name: 'Pikachu',
    type: 'electric',
    level: 10,
    baseStats: { hp: 35, attack: 55, defense: 40, speed: 90 },
    abilities: ['Static'],
    description: 'When several of these Pokémon gather, their electricity could build and cause lightning storms.',
    rarity: 'rare',
    color: '#F8D030',
    isWild: true,
    position: [Math.random() * 20 - 10, 0, Math.random() * 20 - 10],
    evolutionData: { evolvesTo: 'raichu', evolutionCondition: 'Thunder Stone' }
  },
  raichu: {
    id: 'raichu',
    name: 'Raichu',
    type: 'electric',
    level: 25,
    baseStats: { hp: 60, attack: 90, defense: 55, speed: 110 },
    abilities: ['Static'],
    description: 'Its long tail serves as a ground to protect itself from its own high-voltage power.',
    rarity: 'epic',
    color: '#F8D030',
    isWild: false,
    position: [0, 0, 0]
  },

  // Normal/Flying Pokemon
  pidgey: {
    id: 'pidgey',
    name: 'Pidgey',
    type: 'normal',
    secondaryType: 'flying',
    level: 4,
    baseStats: { hp: 40, attack: 45, defense: 40, speed: 56 },
    abilities: ['Keen Eye'],
    description: 'A common sight in forests and woods. It flaps its wings at ground level to kick up blinding sand.',
    rarity: 'common',
    color: '#A8A878',
    isWild: true,
    position: [Math.random() * 30 - 15, 0, Math.random() * 30 - 15],
    evolutionData: { evolvesTo: 'pidgeotto', evolutionLevel: 18 }
  },
  pidgeotto: {
    id: 'pidgeotto',
    name: 'Pidgeotto',
    type: 'normal',
    secondaryType: 'flying',
    level: 18,
    baseStats: { hp: 63, attack: 60, defense: 55, speed: 71 },
    abilities: ['Keen Eye'],
    description: 'Very protective of its sprawling territorial area, this Pokémon will fiercely peck at any intruder.',
    rarity: 'uncommon',
    color: '#A8A878',
    isWild: true,
    position: [Math.random() * 30 - 15, 0, Math.random() * 30 - 15],
    evolutionData: { evolvesTo: 'pidgeot', evolutionLevel: 36 }
  },
  pidgeot: {
    id: 'pidgeot',
    name: 'Pidgeot',
    type: 'normal',
    secondaryType: 'flying',
    level: 36,
    baseStats: { hp: 83, attack: 80, defense: 75, speed: 101 },
    abilities: ['Keen Eye'],
    description: 'When hunting, it skims the surface of water at high speed to pick off unwary prey such as Magikarp.',
    rarity: 'rare',
    color: '#A8A878',
    isWild: false,
    position: [0, 0, 0]
  },

  // Bug Pokemon
  caterpie: {
    id: 'caterpie',
    name: 'Caterpie',
    type: 'bug',
    level: 3,
    baseStats: { hp: 45, attack: 30, defense: 35, speed: 45 },
    abilities: ['Shield Dust'],
    description: 'Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls.',
    rarity: 'common',
    color: '#A8B820',
    isWild: true,
    position: [Math.random() * 30 - 15, 0, Math.random() * 30 - 15],
    evolutionData: { evolvesTo: 'metapod', evolutionLevel: 7 }
  },
  metapod: {
    id: 'metapod',
    name: 'Metapod',
    type: 'bug',
    level: 7,
    baseStats: { hp: 50, attack: 20, defense: 55, speed: 30 },
    abilities: ['Shed Skin'],
    description: 'This Pokémon is vulnerable to attack while its shell is soft, exposing its weak and tender body.',
    rarity: 'common',
    color: '#A8B820',
    isWild: true,
    position: [Math.random() * 30 - 15, 0, Math.random() * 30 - 15],
    evolutionData: { evolvesTo: 'butterfree', evolutionLevel: 10 }
  },
  butterfree: {
    id: 'butterfree',
    name: 'Butterfree',
    type: 'bug',
    secondaryType: 'flying',
    level: 10,
    baseStats: { hp: 60, attack: 45, defense: 50, speed: 70 },
    abilities: ['Compound Eyes'],
    description: 'In battle, it flaps its wings at high speed to release highly toxic dust into the air.',
    rarity: 'uncommon',
    color: '#A8B820',
    isWild: true,
    position: [Math.random() * 30 - 15, 0, Math.random() * 30 - 15]
  },

  // Water Pokemon
  magikarp: {
    id: 'magikarp',
    name: 'Magikarp',
    type: 'water',
    level: 5,
    baseStats: { hp: 20, attack: 10, defense: 55, speed: 80 },
    abilities: ['Swift Swim'],
    description: 'In the distant past, it was somewhat stronger than the horribly weak descendants that exist today.',
    rarity: 'common',
    color: '#6890F0',
    isWild: true,
    position: [Math.random() * 40 - 20, 0, Math.random() * 40 - 20],
    evolutionData: { evolvesTo: 'gyarados', evolutionLevel: 20 }
  },
  gyarados: {
    id: 'gyarados',
    name: 'Gyarados',
    type: 'water',
    secondaryType: 'flying',
    level: 20,
    baseStats: { hp: 95, attack: 125, defense: 79, speed: 81 },
    abilities: ['Intimidate'],
    description: 'Once it appears, its rage never settles until it has razed the fields and mountains around it.',
    rarity: 'epic',
    color: '#6890F0',
    isWild: false,
    position: [0, 0, 0]
  },

  // Legendary Pokemon
  mew: {
    id: 'mew',
    name: 'Mew',
    type: 'psychic',
    level: 50,
    baseStats: { hp: 100, attack: 100, defense: 100, speed: 100 },
    abilities: ['Synchronize'],
    description: 'Because it can learn any move, some people began research to see if it is the ancestor of all Pokémon.',
    rarity: 'legendary',
    color: '#F85888',
    isWild: false,
    position: [0, 0, 0]
  },
  mewtwo: {
    id: 'mewtwo',
    name: 'Mewtwo',
    type: 'psychic',
    level: 70,
    baseStats: { hp: 106, attack: 110, defense: 90, speed: 130 },
    abilities: ['Pressure'],
    description: 'It was created by a scientist after years of horrific gene splicing and DNA engineering experiments.',
    rarity: 'legendary',
    color: '#F85888',
    isWild: false,
    position: [0, 0, 0]
  },
  articuno: {
    id: 'articuno',
    name: 'Articuno',
    type: 'ice',
    secondaryType: 'flying',
    level: 50,
    baseStats: { hp: 90, attack: 85, defense: 100, speed: 85 },
    abilities: ['Pressure'],
    description: 'A legendary bird Pokémon that is said to appear to doomed people who are lost in icy mountains.',
    rarity: 'legendary',
    color: '#98D8D8',
    isWild: false,
    position: [0, 0, 0]
  },
  zapdos: {
    id: 'zapdos',
    name: 'Zapdos',
    type: 'electric',
    secondaryType: 'flying',
    level: 50,
    baseStats: { hp: 90, attack: 90, defense: 85, speed: 100 },
    abilities: ['Pressure'],
    description: 'A legendary bird Pokémon that is said to appear from clouds while dropping enormous lightning bolts.',
    rarity: 'legendary',
    color: '#F8D030',
    isWild: false,
    position: [0, 0, 0]
  },
  moltres: {
    id: 'moltres',
    name: 'Moltres',
    type: 'fire',
    secondaryType: 'flying',
    level: 50,
    baseStats: { hp: 90, attack: 100, defense: 90, speed: 90 },
    abilities: ['Pressure'],
    description: 'Known as the legendary bird of fire. Every flap of its wings creates a dazzling flash of flames.',
    rarity: 'legendary',
    color: '#F08030',
    isWild: false,
    position: [0, 0, 0]
  },

  // Hoopa
  hoopa: {
    id: 'hoopa',
    name: 'Hoopa',
    type: 'psychic',
    secondaryType: 'ghost',
    level: 50,
    baseStats: { hp: 80, attack: 110, defense: 60, speed: 70 },
    abilities: ['Magician'],
    description: 'This troublemaker sends anything and everything to faraway places using its loop, which can warp space.',
    rarity: 'legendary',
    color: '#F85888',
    isWild: false,
    position: [0, 0, 0]
  },

  // More Pokemon for comprehensive database
  geodude: {
    id: 'geodude',
    name: 'Geodude',
    type: 'rock',
    secondaryType: 'ground',
    level: 8,
    baseStats: { hp: 40, attack: 80, defense: 100, speed: 20 },
    abilities: ['Rock Head'],
    description: 'Found in fields and mountains. Mistaking them for boulders, people often step or trip on them.',
    rarity: 'common',
    color: '#B8A038',
    isWild: true,
    position: [Math.random() * 30 - 15, 0, Math.random() * 30 - 15],
    evolutionData: { evolvesTo: 'graveler', evolutionLevel: 25 }
  },
  graveler: {
    id: 'graveler',
    name: 'Graveler',
    type: 'rock',
    secondaryType: 'ground',
    level: 25,
    baseStats: { hp: 55, attack: 95, defense: 115, speed: 35 },
    abilities: ['Rock Head'],
    description: 'Rolls down slopes to move. It rolls over any obstacle without slowing or changing its direction.',
    rarity: 'uncommon',
    color: '#B8A038',
    isWild: true,
    position: [Math.random() * 30 - 15, 0, Math.random() * 30 - 15],
    evolutionData: { evolvesTo: 'golem', evolutionCondition: 'Trade' }
  },
  golem: {
    id: 'golem',
    name: 'Golem',
    type: 'rock',
    secondaryType: 'ground',
    level: 40,
    baseStats: { hp: 80, attack: 120, defense: 130, speed: 45 },
    abilities: ['Rock Head'],
    description: 'Its boulder-like body is extremely hard. It can easily withstand dynamite blasts without damage.',
    rarity: 'rare',
    color: '#B8A038',
    isWild: false,
    position: [0, 0, 0]
  },
  ponyta: {
    id: 'ponyta',
    name: 'Ponyta',
    type: 'fire',
    level: 12,
    baseStats: { hp: 50, attack: 85, defense: 55, speed: 90 },
    abilities: ['Run Away'],
    description: 'Its hooves are 10 times harder than diamonds. It can trample anything completely flat in little time.',
    rarity: 'uncommon',
    color: '#F08030',
    isWild: true,
    position: [Math.random() * 30 - 15, 0, Math.random() * 30 - 15],
    evolutionData: { evolvesTo: 'rapidash', evolutionLevel: 40 }
  },
  rapidash: {
    id: 'rapidash',
    name: 'Rapidash',
    type: 'fire',
    level: 40,
    baseStats: { hp: 65, attack: 100, defense: 70, speed: 105 },
    abilities: ['Run Away'],
    description: 'Very competitive, this Pokémon will chase anything that moves fast in the hopes of racing it.',
    rarity: 'rare',
    color: '#F08030',
    isWild: false,
    position: [0, 0, 0]
  },
  slowpoke: {
    id: 'slowpoke',
    name: 'Slowpoke',
    type: 'water',
    secondaryType: 'psychic',
    level: 15,
    baseStats: { hp: 90, attack: 65, defense: 65, speed: 15 },
    abilities: ['Oblivious'],
    description: 'Incredibly slow and dopey. It takes 5 seconds for it to feel pain when under attack.',
    rarity: 'common',
    color: '#F85888',
    isWild: true,
    position: [Math.random() * 30 - 15, 0, Math.random() * 30 - 15],
    evolutionData: { evolvesTo: 'slowbro', evolutionLevel: 37 }
  },
  slowbro: {
    id: 'slowbro',
    name: 'Slowbro',
    type: 'water',
    secondaryType: 'psychic',
    level: 37,
    baseStats: { hp: 95, attack: 75, defense: 110, speed: 30 },
    abilities: ['Oblivious'],
    description: 'The Shellder that is latched onto Slowpoke\'s tail is said to feed on the host\'s left over scraps.',
    rarity: 'uncommon',
    color: '#F85888',
    isWild: false,
    position: [0, 0, 0]
  },
  magnemite: {
    id: 'magnemite',
    name: 'Magnemite',
    type: 'electric',
    secondaryType: 'steel',
    level: 10,
    baseStats: { hp: 25, attack: 35, defense: 70, speed: 45 },
    abilities: ['Magnet Pull'],
    description: 'Uses anti-gravity to stay suspended. Appears without warning and uses Thunder Wave and similar moves.',
    rarity: 'common',
    color: '#F8D030',
    isWild: true,
    position: [Math.random() * 30 - 15, 0, Math.random() * 30 - 15],
    evolutionData: { evolvesTo: 'magneton', evolutionLevel: 30 }
  },
  magneton: {
    id: 'magneton',
    name: 'Magneton',
    type: 'electric',
    secondaryType: 'steel',
    level: 30,
    baseStats: { hp: 50, attack: 60, defense: 95, speed: 70 },
    abilities: ['Magnet Pull'],
    description: 'Formed by several Magnemites linked together. They frequently appear when sunspots flare up.',
    rarity: 'uncommon',
    color: '#F8D030',
    isWild: true,
    position: [Math.random() * 30 - 15, 0, Math.random() * 30 - 15],
    evolutionData: { evolvesTo: 'magnezone', evolutionCondition: 'Level up in special area' }
  },
  farfetchd: {
    id: 'farfetchd',
    name: 'Farfetch\'d',
    type: 'normal',
    secondaryType: 'flying',
    level: 20,
    baseStats: { hp: 52, attack: 90, defense: 55, speed: 60 },
    abilities: ['Keen Eye'],
    description: 'The plant stalk it holds is its weapon. The stalk is used like a sword to cut all sorts of things.',
    rarity: 'rare',
    color: '#A8A878',
    isWild: true,
    position: [Math.random() * 30 - 15, 0, Math.random() * 30 - 15]
  },
  doduo: {
    id: 'doduo',
    name: 'Doduo',
    type: 'normal',
    secondaryType: 'flying',
    level: 16,
    baseStats: { hp: 35, attack: 85, defense: 45, speed: 75 },
    abilities: ['Run Away'],
    description: 'A bird that makes up for its poor flying with its fast foot speed. Leaves giant footprints.',
    rarity: 'common',
    color: '#A8A878',
    isWild: true,
    position: [Math.random() * 30 - 15, 0, Math.random() * 30 - 15],
    evolutionData: { evolvesTo: 'dodrio', evolutionLevel: 31 }
  },
  dodrio: {
    id: 'dodrio',
    name: 'Dodrio',
    type: 'normal',
    secondaryType: 'flying',
    level: 31,
    baseStats: { hp: 60, attack: 110, defense: 70, speed: 110 },
    abilities: ['Run Away'],
    description: 'Uses its three brains to execute complex plans. While two heads sleep, one head stays awake.',
    rarity: 'uncommon',
    color: '#A8A878',
    isWild: true,
    position: [Math.random() * 30 - 15, 0, Math.random() * 30 - 15]
  },
  seel: {
    id: 'seel',
    name: 'Seel',
    type: 'water',
    level: 18,
    baseStats: { hp: 65, attack: 45, defense: 55, speed: 45 },
    abilities: ['Thick Fat'],
    description: 'The protruding horn on its head is very hard. It is used for bashing through thick ice.',
    rarity: 'common',
    color: '#6890F0',
    isWild: true,
    position: [Math.random() * 30 - 15, 0, Math.random() * 30 - 15],
    evolutionData: { evolvesTo: 'dewgong', evolutionLevel: 34 }
  },
  dewgong: {
    id: 'dewgong',
    name: 'Dewgong',
    type: 'water',
    secondaryType: 'ice',
    level: 34,
    baseStats: { hp: 90, attack: 70, defense: 80, speed: 70 },
    abilities: ['Thick Fat'],
    description: 'Stores thermal energy in its body. Swims at a steady 8 knots even in intensely cold waters.',
    rarity: 'uncommon',
    color: '#6890F0',
    isWild: false,
    position: [0, 0, 0]
  },
  grimer: {
    id: 'grimer',
    name: 'Grimer',
    type: 'poison',
    level: 12,
    baseStats: { hp: 80, attack: 80, defense: 50, speed: 25 },
    abilities: ['Stench'],
    description: 'Appears in filthy areas. Thrives by sucking up polluted sludge that is pumped out of factories.',
    rarity: 'common',
    color: '#A040A0',
    isWild: true,
    position: [Math.random() * 30 - 15, 0, Math.random() * 30 - 15],
    evolutionData: { evolvesTo: 'muk', evolutionLevel: 38 }
  },
  muk: {
    id: 'muk',
    name: 'Muk',
    type: 'poison',
    level: 38,
    baseStats: { hp: 105, attack: 105, defense: 75, speed: 50 },
    abilities: ['Stench'],
    description: 'Thickly covered with a filthy, vile sludge. It is so toxic that even its footprints contain poison.',
    rarity: 'uncommon',
    color: '#A040A0',
    isWild: false,
    position: [0, 0, 0]
  },
  shellder: {
    id: 'shellder',
    name: 'Shellder',
    type: 'water',
    level: 14,
    baseStats: { hp: 30, attack: 65, defense: 100, speed: 40 },
    abilities: ['Shell Armor'],
    description: 'Its hard shell repels any kind of attack. It is vulnerable only when its shell is open.',
    rarity: 'common',
    color: '#6890F0',
    isWild: true,
    position: [Math.random() * 30 - 15, 0, Math.random() * 30 - 15],
    evolutionData: { evolvesTo: 'cloyster', evolutionCondition: 'Water Stone' }
  },
  cloyster: {
    id: 'cloyster',
    name: 'Cloyster',
    type: 'water',
    secondaryType: 'ice',
    level: 25,
    baseStats: { hp: 50, attack: 95, defense: 180, speed: 70 },
    abilities: ['Shell Armor'],
    description: 'When attacked, it launches its horns in quick volleys. Its innards have never been seen.',
    rarity: 'rare',
    color: '#6890F0',
    isWild: false,
    position: [0, 0, 0]
  },
  gastly: {
    id: 'gastly',
    name: 'Gastly',
    type: 'ghost',
    secondaryType: 'poison',
    level: 8,
    baseStats: { hp: 30, attack: 35, defense: 30, speed: 80 },
    abilities: ['Levitate'],
    description: 'Almost invisible, this gaseous Pokémon cloaks the target and puts it to sleep without notice.',
    rarity: 'uncommon',
    color: '#705898',
    isWild: true,
    position: [Math.random() * 30 - 15, 0, Math.random() * 30 - 15],
    evolutionData: { evolvesTo: 'haunter', evolutionLevel: 25 }
  },
  haunter: {
    id: 'haunter',
    name: 'Haunter',
    type: 'ghost',
    secondaryType: 'poison',
    level: 25,
    baseStats: { hp: 45, attack: 50, defense: 45, speed: 95 },
    abilities: ['Levitate'],
    description: 'Because of its ability to slip through block walls, it is said to be from another dimension.',
    rarity: 'rare',
    color: '#705898',
    isWild: true,
    position: [Math.random() * 30 - 15, 0, Math.random() * 30 - 15],
    evolutionData: { evolvesTo: 'gengar', evolutionCondition: 'Trade' }
  },
  gengar: {
    id: 'gengar',
    name: 'Gengar',
    type: 'ghost',
    secondaryType: 'poison',
    level: 35,
    baseStats: { hp: 60, attack: 65, defense: 60, speed: 110 },
    abilities: ['Cursed Body'],
    description: 'Under a full moon, this Pokémon likes to mimic the shadows of people and laugh at their fright.',
    rarity: 'epic',
    color: '#705898',
    isWild: false,
    position: [0, 0, 0]
  },
  onix: {
    id: 'onix',
    name: 'Onix',
    type: 'rock',
    secondaryType: 'ground',
    level: 20,
    baseStats: { hp: 35, attack: 45, defense: 160, speed: 70 },
    abilities: ['Rock Head'],
    description: 'As it grows, the stone portions of its body harden to become similar to a diamond, but colored black.',
    rarity: 'uncommon',
    color: '#B8A038',
    isWild: true,
    position: [Math.random() * 30 - 15, 0, Math.random() * 30 - 15],
    evolutionData: { evolvesTo: 'steelix', evolutionCondition: 'Trade with Metal Coat' }
  },
  drowzee: {
    id: 'drowzee',
    name: 'Drowzee',
    type: 'psychic',
    level: 16,
    baseStats: { hp: 60, attack: 48, defense: 45, speed: 42 },
    abilities: ['Insomnia'],
    description: 'Puts enemies to sleep then eats their dreams. Occasionally gets sick from eating bad dreams.',
    rarity: 'common',
    color: '#F85888',
    isWild: true,
    position: [Math.random() * 30 - 15, 0, Math.random() * 30 - 15],
    evolutionData: { evolvesTo: 'hypno', evolutionLevel: 26 }
  },
  hypno: {
    id: 'hypno',
    name: 'Hypno',
    type: 'psychic',
    level: 26,
    baseStats: { hp: 85, attack: 73, defense: 70, speed: 67 },
    abilities: ['Insomnia'],
    description: 'When it locks eyes with an enemy, it will use a mix of psi powers such as Hypnosis and Confusion.',
    rarity: 'uncommon',
    color: '#F85888',
    isWild: true,
    position: [Math.random() * 30 - 15, 0, Math.random() * 30 - 15]
  },
  krabby: {
    id: 'krabby',
    name: 'Krabby',
    type: 'water',
    level: 12,
    baseStats: { hp: 30, attack: 105, defense: 90, speed: 50 },
    abilities: ['Hyper Cutter'],
    description: 'Its pincers are not only powerful, they are also very dexterous. It can use them to pick up small items.',
    rarity: 'common',
    color: '#6890F0',
    isWild: true,
    position: [Math.random() * 30 - 15, 0, Math.random() * 30 - 15],
    evolutionData: { evolvesTo: 'kingler', evolutionLevel: 28 }
  },
  kingler: {
    id: 'kingler',
    name: 'Kingler',
    type: 'water',
    level: 28,
    baseStats: { hp: 55, attack: 130, defense: 115, speed: 75 },
    abilities: ['Hyper Cutter'],
    description: 'The large pincer has 10000 hp of crushing power. However, its huge size makes it unwieldy to use.',
    rarity: 'uncommon',
    color: '#6890F0',
    isWild: false,
    position: [0, 0, 0]
  },
  voltorb: {
    id: 'voltorb',
    name: 'Voltorb',
    type: 'electric',
    level: 10,
    baseStats: { hp: 40, attack: 30, defense: 50, speed: 100 },
    abilities: ['Soundproof'],
    description: 'Usually found in power plants. Easily mistaken for a Poké Ball, they have zapped many people.',
    rarity: 'common',
    color: '#F8D030',
    isWild: true,
    position: [Math.random() * 30 - 15, 0, Math.random() * 30 - 15],
    evolutionData: { evolvesTo: 'electrode', evolutionLevel: 30 }
  },
  electrode: {
    id: 'electrode',
    name: 'Electrode',
    type: 'electric',
    level: 30,
    baseStats: { hp: 60, attack: 50, defense: 70, speed: 150 },
    abilities: ['Soundproof'],
    description: 'It stores electric energy under very high pressure. It often explodes with little or no provocation.',
    rarity: 'uncommon',
    color: '#F8D030',
    isWild: false,
    position: [0, 0, 0]
  },
  exeggcute: {
    id: 'exeggcute',
    name: 'Exeggcute',
    type: 'grass',
    secondaryType: 'psychic',
    level: 14,
    baseStats: { hp: 60, attack: 40, defense: 80, speed: 40 },
    abilities: ['Chlorophyll'],
    description: 'This Pokémon consists of six eggs that form a closely knit cluster. The six eggs attract each other.',
    rarity: 'uncommon',
    color: '#78C850',
    isWild: true,
    position: [Math.random() * 30 - 15, 0, Math.random() * 30 - 15],
    evolutionData: { evolvesTo: 'exeggutor', evolutionCondition: 'Leaf Stone' }
  },
  exeggutor: {
    id: 'exeggutor',
    name: 'Exeggutor',
    type: 'grass',
    secondaryType: 'psychic',
    level: 25,
    baseStats: { hp: 95, attack: 95, defense: 85, speed: 55 },
    abilities: ['Chlorophyll'],
    description: 'Legend has it that on rare occasions, one of its heads will drop off and continue living as an Exeggcute.',
    rarity: 'rare',
    color: '#78C850',
    isWild: false,
    position: [0, 0, 0]
  },
  cubone: {
    id: 'cubone',
    name: 'Cubone',
    type: 'ground',
    level: 12,
    baseStats: { hp: 50, attack: 50, defense: 95, speed: 35 },
    abilities: ['Rock Head'],
    description: 'Because it never removes its skull helmet, no one has ever seen this Pokémon\'s real face.',
    rarity: 'uncommon',
    color: '#E0C068',
    isWild: true,
    position: [Math.random() * 30 - 15, 0, Math.random() * 30 - 15],
    evolutionData: { evolvesTo: 'marowak', evolutionLevel: 28 }
  },
  marowak: {
    id: 'marowak',
    name: 'Marowak',
    type: 'ground',
    level: 28,
    baseStats: { hp: 60, attack: 80, defense: 110, speed: 45 },
    abilities: ['Rock Head'],
    description: 'The bone it holds is its key weapon. It throws the bone skillfully like a boomerang to KO targets.',
    rarity: 'rare',
    color: '#E0C068',
    isWild: false,
    position: [0, 0, 0]
  },
  hitmonlee: {
    id: 'hitmonlee',
    name: 'Hitmonlee',
    type: 'fighting',
    level: 30,
    baseStats: { hp: 50, attack: 120, defense: 53, speed: 87 },
    abilities: ['Limber'],
    description: 'When in a hurry, its legs lengthen progressively. It runs smoothly with extra long, loping strides.',
    rarity: 'rare',
    color: '#C03028',
    isWild: false,
    position: [0, 0, 0]
  },
  hitmonchan: {
    id: 'hitmonchan',
    name: 'Hitmonchan',
    type: 'fighting',
    level: 30,
    baseStats: { hp: 50, attack: 105, defense: 79, speed: 76 },
    abilities: ['Keen Eye'],
    description: 'While apparently doing nothing, it fires punches in lightning fast volleys that are impossible to see.',
    rarity: 'rare',
    color: '#C03028',
    isWild: false,
    position: [0, 0, 0]
  },
  lickitung: {
    id: 'lickitung',
    name: 'Lickitung',
    type: 'normal',
    level: 18,
    baseStats: { hp: 90, attack: 55, defense: 75, speed: 30 },
    abilities: ['Own Tempo'],
    description: 'Its tongue can be extended like a chameleon\'s. It leaves a tingling sensation when it licks enemies.',
    rarity: 'uncommon',
    color: '#A8A878',
    isWild: true,
    position: [Math.random() * 30 - 15, 0, Math.random() * 30 - 15]
  },
  koffing: {
    id: 'koffing',
    name: 'Koffing',
    type: 'poison',
    level: 15,
    baseStats: { hp: 40, attack: 65, defense: 95, speed: 35 },
    abilities: ['Levitate'],
    description: 'Because it stores several kinds of toxic gases in its body, it is prone to exploding without warning.',
    rarity: 'common',
    color: '#A040A0',
    isWild: true,
    position: [Math.random() * 30 - 15, 0, Math.random() * 30 - 15],
    evolutionData: { evolvesTo: 'weezing', evolutionLevel: 35 }
  },
  weezing: {
    id: 'weezing',
    name: 'Weezing',
    type: 'poison',
    level: 35,
    baseStats: { hp: 65, attack: 90, defense: 120, speed: 60 },
    abilities: ['Levitate'],
    description: 'Where two kinds of poison gases meet, 2 Koffings can fuse into a Weezing over many years.',
    rarity: 'uncommon',
    color: '#A040A0',
    isWild: false,
    position: [0, 0, 0]
  },
  rhyhorn: {
    id: 'rhyhorn',
    name: 'Rhyhorn',
    type: 'ground',
    secondaryType: 'rock',
    level: 18,
    baseStats: { hp: 80, attack: 85, defense: 95, speed: 25 },
    abilities: ['Lightning Rod'],
    description: 'Its massive bones are 1000 times harder than human bones. It can easily knock a trailer flying.',
    rarity: 'uncommon',
    color: '#E0C068',
    isWild: true,
    position: [Math.random() * 30 - 15, 0, Math.random() * 30 - 15],
    evolutionData: { evolvesTo: 'rhydon', evolutionLevel: 42 }
  },
  rhydon: {
    id: 'rhydon',
    name: 'Rhydon',
    type: 'ground',
    secondaryType: 'rock',
    level: 42,
    baseStats: { hp: 105, attack: 130, defense: 120, speed: 40 },
    abilities: ['Lightning Rod'],
    description: 'Protected by an armor-like hide, it is capable of living in molten lava of 3,600 degrees.',
    rarity: 'rare',
    color: '#E0C068',
    isWild: false,
    position: [0, 0, 0]
  },
  chansey: {
    id: 'chansey',
    name: 'Chansey',
    type: 'normal',
    level: 25,
    baseStats: { hp: 250, attack: 5, defense: 5, speed: 50 },
    abilities: ['Natural Cure'],
    description: 'A rare and elusive Pokémon that is said to bring happiness to those who manage to get it.',
    rarity: 'epic',
    color: '#A8A878',
    isWild: true,
    position: [Math.random() * 10 - 5, 0, Math.random() * 10 - 5]
  },
  tangela: {
    id: 'tangela',
    name: 'Tangela',
    type: 'grass',
    level: 22,
    baseStats: { hp: 65, attack: 55, defense: 115, speed: 60 },
    abilities: ['Chlorophyll'],
    description: 'The whole body is swathed with wide vines that are similar to seaweed. Its vines shake as it walks.',
    rarity: 'uncommon',
    color: '#78C850',
    isWild: true,
    position: [Math.random() * 30 - 15, 0, Math.random() * 30 - 15]
  },
  kangaskhan: {
    id: 'kangaskhan',
    name: 'Kangaskhan',
    type: 'normal',
    level: 30,
    baseStats: { hp: 105, attack: 95, defense: 80, speed: 90 },
    abilities: ['Early Bird'],
    description: 'The infant rarely ventures out of its mother\'s protective pouch until it is 3 years old.',
    rarity: 'epic',
    color: '#A8A878',
    isWild: true,
    position: [Math.random() * 20 - 10, 0, Math.random() * 20 - 10]
  },
  horsea: {
    id: 'horsea',
    name: 'Horsea',
    type: 'water',
    level: 8,
    baseStats: { hp: 30, attack: 40, defense: 70, speed: 60 },
    abilities: ['Swift Swim'],
    description: 'Known to shoot down flying bugs with precision blasts of ink from the surface of the water.',
    rarity: 'common',
    color: '#6890F0',
    isWild: true,
    position: [Math.random() * 30 - 15, 0, Math.random() * 30 - 15],
    evolutionData: { evolvesTo: 'seadra', evolutionLevel: 32 }
  },
  seadra: {
    id: 'seadra',
    name: 'Seadra',
    type: 'water',
    level: 32,
    baseStats: { hp: 55, attack: 65, defense: 95, speed: 85 },
    abilities: ['Poison Point'],
    description: 'Capable of swimming backwards by rapidly flapping its wing-like pectoral fins and stout tail.',
    rarity: 'uncommon',
    color: '#6890F0',
    isWild: false,
    position: [0, 0, 0]
  },
  goldeen: {
    id: 'goldeen',
    name: 'Goldeen',
    type: 'water',
    level: 12,
    baseStats: { hp: 45, attack: 67, defense: 60, speed: 63 },
    abilities: ['Swift Swim'],
    description: 'Its tail fin billows like an elegant ballroom dress, giving it the nickname of the Water Queen.',
    rarity: 'common',
    color: '#6890F0',
    isWild: true,
    position: [Math.random() * 30 - 15, 0, Math.random() * 30 - 15],
    evolutionData: { evolvesTo: 'seaking', evolutionLevel: 33 }
  },
  seaking: {
    id: 'seaking',
    name: 'Seaking',
    type: 'water',
    level: 33,
    baseStats: { hp: 80, attack: 92, defense: 65, speed: 68 },
    abilities: ['Swift Swim'],
    description: 'In the autumn spawning season, they can be seen swimming powerfully up rivers and creeks.',
    rarity: 'uncommon',
    color: '#6890F0',
    isWild: false,
    position: [0, 0, 0]
  },
  staryu: {
    id: 'staryu',
    name: 'Staryu',
    type: 'water',
    level: 15,
    baseStats: { hp: 30, attack: 45, defense: 55, speed: 85 },
    abilities: ['Illuminate'],
    description: 'An enigmatic Pokémon that can effortlessly regenerate any appendage it loses in battle.',
    rarity: 'common',
    color: '#6890F0',
    isWild: true,
    position: [Math.random() * 30 - 15, 0, Math.random() * 30 - 15],
    evolutionData: { evolvesTo: 'starmie', evolutionCondition: 'Water Stone' }
  },
  starmie: {
    id: 'starmie',
    name: 'Starmie',
    type: 'water',
    secondaryType: 'psychic',
    level: 25,
    baseStats: { hp: 60, attack: 75, defense: 85, speed: 115 },
    abilities: ['Illuminate'],
    description: 'Its central core glows with the seven colors of the rainbow. Some people value the core as a gem.',
    rarity: 'rare',
    color: '#6890F0',
    isWild: false,
    position: [0, 0, 0]
  },
  mr_mime: {
    id: 'mr_mime',
    name: 'Mr. Mime',
    type: 'psychic',
    secondaryType: 'fairy',
    level: 25,
    baseStats: { hp: 40, attack: 45, defense: 65, speed: 90 },
    abilities: ['Soundproof'],
    description: 'If interrupted while it is miming, it will slap around the offender with its broad hands.',
    rarity: 'rare',
    color: '#F85888',
    isWild: true,
    position: [Math.random() * 20 - 10, 0, Math.random() * 20 - 10]
  },
  scyther: {
    id: 'scyther',
    name: 'Scyther',
    type: 'bug',
    secondaryType: 'flying',
    level: 25,
    baseStats: { hp: 70, attack: 110, defense: 80, speed: 105 },
    abilities: ['Swarm'],
    description: 'With ninja-like agility and speed, it can create the illusion that there is more than one.',
    rarity: 'rare',
    color: '#A8B820',
    isWild: true,
    position: [Math.random() * 20 - 10, 0, Math.random() * 20 - 10]
  },
  jynx: {
    id: 'jynx',
    name: 'Jynx',
    type: 'ice',
    secondaryType: 'psychic',
    level: 30,
    baseStats: { hp: 65, attack: 50, defense: 35, speed: 95 },
    abilities: ['Oblivious'],
    description: 'It seductively wiggles its hips as it walks. It can cause people to dance in unison with it.',
    rarity: 'rare',
    color: '#98D8D8',
    isWild: true,
    position: [Math.random() * 20 - 10, 0, Math.random() * 20 - 10]
  },
  electabuzz: {
    id: 'electabuzz',
    name: 'Electabuzz',
    type: 'electric',
    level: 30,
    baseStats: { hp: 65, attack: 83, defense: 57, speed: 105 },
    abilities: ['Static'],
    description: 'Normally found near power plants, they can wander away and cause major blackouts in cities.',
    rarity: 'rare',
    color: '#F8D030',
    isWild: true,
    position: [Math.random() * 20 - 10, 0, Math.random() * 20 - 10]
  },
  magmar: {
    id: 'magmar',
    name: 'Magmar',
    type: 'fire',
    level: 30,
    baseStats: { hp: 65, attack: 95, defense: 57, speed: 93 },
    abilities: ['Flame Body'],
    description: 'Its body always burns with an orange glow that enables it to hide perfectly among flames.',
    rarity: 'rare',
    color: '#F08030',
    isWild: true,
    position: [Math.random() * 20 - 10, 0, Math.random() * 20 - 10]
  },
  pinsir: {
    id: 'pinsir',
    name: 'Pinsir',
    type: 'bug',
    level: 25,
    baseStats: { hp: 65, attack: 125, defense: 100, speed: 85 },
    abilities: ['Hyper Cutter'],
    description: 'If it fails to crush the victim in its pincers, it will swing it around and toss it hard.',
    rarity: 'rare',
    color: '#A8B820',
    isWild: true,
    position: [Math.random() * 20 - 10, 0, Math.random() * 20 - 10]
  },
  tauros: {
    id: 'tauros',
    name: 'Tauros',
    type: 'normal',
    level: 25,
    baseStats: { hp: 75, attack: 100, defense: 95, speed: 110 },
    abilities: ['Intimidate'],
    description: 'When it targets an enemy, it charges furiously while whipping its body with its long tails.',
    rarity: 'rare',
    color: '#A8A878',
    isWild: true,
    position: [Math.random() * 20 - 10, 0, Math.random() * 20 - 10]
  },
  lapras: {
    id: 'lapras',
    name: 'Lapras',
    type: 'water',
    secondaryType: 'ice',
    level: 30,
    baseStats: { hp: 130, attack: 85, defense: 80, speed: 60 },
    abilities: ['Water Absorb'],
    description: 'A Pokémon that has been overhunted almost to extinction. It can ferry people across bodies of water.',
    rarity: 'epic',
    color: '#6890F0',
    isWild: true,
    position: [Math.random() * 10 - 5, 0, Math.random() * 10 - 5]
  },
  ditto: {
    id: 'ditto',
    name: 'Ditto',
    type: 'normal',
    level: 20,
    baseStats: { hp: 48, attack: 48, defense: 48, speed: 48 },
    abilities: ['Limber'],
    description: 'Capable of copying an enemy\'s genetic code to instantly transform itself into a duplicate of the enemy.',
    rarity: 'epic',
    color: '#A8A878',
    isWild: true,
    position: [Math.random() * 15 - 7, 0, Math.random() * 15 - 7]
  },
  eevee: {
    id: 'eevee',
    name: 'Eevee',
    type: 'normal',
    level: 10,
    baseStats: { hp: 55, attack: 55, defense: 50, speed: 55 },
    abilities: ['Run Away'],
    description: 'Thanks to its unstable genetic makeup, this special Pokémon conceals many different possible evolutions.',
    rarity: 'rare',
    color: '#A8A878',
    isWild: true,
    position: [Math.random() * 20 - 10, 0, Math.random() * 20 - 10],
    evolutionData: { evolvesTo: 'vaporeon', evolutionCondition: 'Water Stone' }
  },
  vaporeon: {
    id: 'vaporeon',
    name: 'Vaporeon',
    type: 'water',
    level: 25,
    baseStats: { hp: 130, attack: 65, defense: 60, speed: 65 },
    abilities: ['Water Absorb'],
    description: 'Lives close to water. Its long tail is ridged with a fin which is often mistaken for a mermaid\'s.',
    rarity: 'epic',
    color: '#6890F0',
    isWild: false,
    position: [0, 0, 0]
  },
  jolteon: {
    id: 'jolteon',
    name: 'Jolteon',
    type: 'electric',
    level: 25,
    baseStats: { hp: 65, attack: 65, defense: 60, speed: 130 },
    abilities: ['Volt Absorb'],
    description: 'It accumulates negative ions in the atmosphere to blast out 10000-volt lightning bolts.',
    rarity: 'epic',
    color: '#F8D030',
    isWild: false,
    position: [0, 0, 0]
  },
  flareon: {
    id: 'flareon',
    name: 'Flareon',
    type: 'fire',
    level: 25,
    baseStats: { hp: 65, attack: 130, defense: 60, speed: 65 },
    abilities: ['Flash Fire'],
    description: 'When storing thermal energy in its body, its temperature could soar to over 1600 degrees.',
    rarity: 'epic',
    color: '#F08030',
    isWild: false,
    position: [0, 0, 0]
  },
  porygon: {
    id: 'porygon',
    name: 'Porygon',
    type: 'normal',
    level: 25,
    baseStats: { hp: 65, attack: 60, defense: 70, speed: 40 },
    abilities: ['Trace'],
    description: 'A Pokémon that consists entirely of programming code. Capable of moving freely in cyberspace.',
    rarity: 'rare',
    color: '#A8A878',
    isWild: false,
    position: [0, 0, 0]
  },
  omanyte: {
    id: 'omanyte',
    name: 'Omanyte',
    type: 'rock',
    secondaryType: 'water',
    level: 20,
    baseStats: { hp: 35, attack: 40, defense: 100, speed: 35 },
    abilities: ['Swift Swim'],
    description: 'Although long extinct, in rare cases, it can be genetically resurrected from fossils.',
    rarity: 'rare',
    color: '#B8A038',
    isWild: false,
    position: [0, 0, 0],
    evolutionData: { evolvesTo: 'omastar', evolutionLevel: 40 }
  },
  omastar: {
    id: 'omastar',
    name: 'Omastar',
    type: 'rock',
    secondaryType: 'water',
    level: 40,
    baseStats: { hp: 70, attack: 60, defense: 125, speed: 55 },
    abilities: ['Swift Swim'],
    description: 'A prehistoric Pokémon that died out when its heavy shell made it impossible to catch prey.',
    rarity: 'epic',
    color: '#B8A038',
    isWild: false,
    position: [0, 0, 0]
  },
  kabuto: {
    id: 'kabuto',
    name: 'Kabuto',
    type: 'rock',
    secondaryType: 'water',
    level: 20,
    baseStats: { hp: 30, attack: 80, defense: 90, speed: 55 },
    abilities: ['Swift Swim'],
    description: 'A Pokémon that was resurrected from a fossil found in what was once the ocean floor eons ago.',
    rarity: 'rare',
    color: '#B8A038',
    isWild: false,
    position: [0, 0, 0],
    evolutionData: { evolvesTo: 'kabutops', evolutionLevel: 40 }
  },
  kabutops: {
    id: 'kabutops',
    name: 'Kabutops',
    type: 'rock',
    secondaryType: 'water',
    level: 40,
    baseStats: { hp: 60, attack: 115, defense: 105, speed: 80 },
    abilities: ['Swift Swim'],
    description: 'Its sleek shape is perfect for swimming. It slashes prey with its claws and drains the body fluids.',
    rarity: 'epic',
    color: '#B8A038',
    isWild: false,
    position: [0, 0, 0]
  },
  aerodactyl: {
    id: 'aerodactyl',
    name: 'Aerodactyl',
    type: 'rock',
    secondaryType: 'flying',
    level: 30,
    baseStats: { hp: 80, attack: 105, defense: 65, speed: 130 },
    abilities: ['Rock Head'],
    description: 'A ferocious, prehistoric Pokémon that goes for the enemy\'s throat with its serrated saw-like fangs.',
    rarity: 'epic',
    color: '#B8A038',
    isWild: false,
    position: [0, 0, 0]
  },
  snorlax: {
    id: 'snorlax',
    name: 'Snorlax',
    type: 'normal',
    level: 30,
    baseStats: { hp: 160, attack: 110, defense: 65, speed: 30 },
    abilities: ['Immunity'],
    description: 'Very lazy. Just eats and sleeps. As its rotund bulk builds, it becomes steadily more slothful.',
    rarity: 'epic',
    color: '#A8A878',
    isWild: true,
    position: [Math.random() * 10 - 5, 0, Math.random() * 10 - 5]
  },
  dragonite: {
    id: 'dragonite',
    name: 'Dragonite',
    type: 'dragon',
    secondaryType: 'flying',
    level: 55,
    baseStats: { hp: 91, attack: 134, defense: 95, speed: 80 },
    abilities: ['Inner Focus'],
    description: 'An extremely rarely seen marine Pokémon. Its intelligence is said to match that of humans.',
    rarity: 'legendary',
    color: '#7038F8',
    isWild: false,
    position: [0, 0, 0]
  }
};

console.log(`Loaded ${Object.keys(eliteDatabase).length} Pokemon into elite database`);